### ISSUE TITLE
Visualize modules graphically via the `cargo-modules` crate

### ISSUE THREAD

**Issue by mattcristal** [mainmatter/100-exercises-to-learn-rust#101]
# Description

I am currently working on the `03_modules` exercise and I found out about this crate [cargo-modules](https://crates.io/crates/cargo-modules) which is quite nice. Perhaps it can be suggested as an optional resource?

Below, a usage example 👇🏼  

```shell
❯ cargo modules structure --package modules

crate modules
├── struct Ticket: pub(crate)
│   └── fn new: pub(crate)
└── mod helpers: pub(crate)
    └── fn create_todo_ticket: pub(self)
```

![cargo_modules](https://github.com/mainmatter/100-exercises-to-learn-rust/assets/33809495/413badac-3158-43ef-9dac-834898bb49e1)

**Comment by LukeMathWalker** [comment]
Good idea, thanks for the suggestion!
