### ISSUE TITLE
07_threads/03_leak typo: Box::leak => v.leak()

### ISSUE THREAD

**Issue by eugenefil** [mainmatter/100-exercises-to-learn-rust#105]
In the code example of section [Data leakage is process-scoped](https://rust-exercises.com/07_threads/03_leak#data-leakage-is-process-scoped) the vector is leaked via `Box::leak` which expects `Box`. Shouldn't it be `v.leak()` instead?

**Comment by LukeMathWalker** [comment]
Yes, you're right! Would you mind filing a PR?
