### ISSUE TITLE
Question about 05_ticket_v2/14_source

### ISSUE THREAD

**Issue by dellos** [mainmatter/100-exercises-to-learn-rust#123]
I failed to pass `assert!(err.source().is_some());`

My thought:
in `pub fn new(title: String, description: String, status: String) -> Result<Self, TicketNewError>{...}`
own error is TicketNewError.
but inside this function, there is a change that ` ParseStatusError` will present.
so we need a code to convert it.
``` 
 let status = match Status::try_from(status) {
            Ok(s) => s,
            Err(e) => return Err(TicketNewError::InvalidStatus{source: e}), // wrap to TicketNewError
        };
```
in TickNewError
```
#[derive(Debug, thiserror::Error)]
pub enum TicketNewError {
...
   #[error(transparent)]             //sepcific use the source error???
    InvalidStatus {source: ParseStatusError},
}
```
but do some the source will type of ParseStatusError not Some(ParseStatusError).

if I impl the `std::error::Error` for `TicketNewError` it will lead to conflict impl.

**Comment by LukeMathWalker** [comment]
> but do some the source will type of ParseStatusError not Some(ParseStatusError).

The auto-generated `std::error::Error` implementation will return the correct type, it wouldn't compile otherwise!
No need to add a manual implementation.
