### ISSUE TITLE
how to (re-) run an exercise?

### ISSUE THREAD

**Issue by richsalz** [mainmatter/100-exercises-to-learn-rust#152]
I want to play around with an exercise after finishing it.  What's the cargo command/config/whatever to do that outside of the "wr" framework which is not what I want?

**Comment by c-git** [comment]
You can just navigate into that folder and run `cargo test`.

**Comment by richsalz** [comment]
tnx.

**Comment by hdoordt** [comment]
@richsalz Looks like your question was answered, closing this issue now. Good luck!
