### ISSUE TITLE
Faulty solution for Chapter 06 Ticket Management, 13 Index

### ISSUE THREAD

**Issue by 0x006E** [mainmatter/100-exercises-to-learn-rust#16]
The solution for implementing Index<&TicketId> is written like this:
```
impl Index<&TicketId> for TicketStore {
    type Output = Ticket;

    fn index(&self, id: &TicketId) -> &Self::Output {
        &self[*id]
    }
}
```

Here `self` refers to the TicketStore {counter: u64, tickets: Vec<Ticket>}. So the index function should not work. 

The fix should be to change it to
```
impl Index<&TicketId> for TicketStore {
    type Output = Ticket;

    fn index(&self, id: &TicketId) -> &Self::Output {
        self.tickets.iter().find(|t| t.id == *id).unwrap()
    }
}
```

which is the same implementation as Index<TicketId>

edits: fix code formatting

**Comment by 0x006E** [comment]
This was my bad!
I didn't think enough before creating this issue. &TicketId indexing uses the TicketId index we created

**Comment by nkl3in** [comment]
Thank you for your comment and explanation
