### ISSUE TITLE
6.5 Iter exercise

### ISSUE THREAD

**Issue by drguildo** [mainmatter/100-exercises-to-learn-rust#163]
Thanks for creating the course and making it available. I'm learning a lot from it.

Doing exercise 6.5 Iter seems to require a return type of `impl Iterator<Item = &Ticket>`, but AFAIK returning an `impl` hasn't been covered in the book yet. Did I overlook something, or is there another way of solving it without resorting to an `impl` return type?

**Comment by hdoordt** [comment]
It sure is the more ergonomic way of doing it, but you can also solve this one by setting up your own struct that implements Iterator. That is the learning objective of this exercise.

Or you can explicitly name the one you're using, but that means digging through the docs of std.

**Comment by LukeMathWalker** [comment]
You can find the expected solution [here](https://github.com/mainmatter/100-exercises-to-learn-rust/blob/solutions/exercises%2F06_ticket_management%2F05_iter%2Fsrc%2Flib.rs#L34).

At this stage, you're not expected to know about `impl` trait syntax nor implement your own iterator. You just need to leverage the iterators available in the standard library on the underlying collection.

**Comment by drguildo** [comment]
@hdoordt Doesn't that involve the use of lifetimes; something that hasn't been covered yet?

@LukeMathWalker I think slices are another topic that haven't been covered at this point.

**Comment by drguildo** [comment]
The next exercise on lifetimes has the same issue where I really think not enough information was given to solve the exercise. In this case I think the issue is more the syntax rather than missing concepts.

The section doesn't mention anything about using lifetime parameters after the `impl`, or using them on the Item and IntoIter associated types, and I don't feel there was enough information to make that leap myself. Maybe I'm just dumb. I have some understanding of lifetimes already and this is too much for me, so I don't know how somebody completely new to Rust is supposed to solve it without going off and reading a load of other stuff.

**Comment by LukeMathWalker** [comment]
> @hdoordt Doesn't that involve the use of lifetimes; something that hasn't been covered yet?
> 
> @LukeMathWalker I think slices are another topic that haven't been covered at this point.

The solution doesn't require slices, it just requires using a type in the `std::slice` module. 
This exercise is somewhat more difficult than others because it actively requires you to go through the documentation of the standard library to get familiar with its methods and how trait implementations are represented, but that's by design.
