### ISSUE TITLE
String interpolation not covered yet in unwrap exercise

### ISSUE THREAD

**Issue by louwers** [mainmatter/100-exercises-to-learn-rust#182]
For the [Unwrap](https://rust-exercises.com/100-exercises/05_ticket_v2/07_unwrap) exercise string interpolation is needed.

Correct me if I'm wrong, but I don't think it's covered at that point.

**Comment by LukeMathWalker** [comment]
It is indeed correct.

At the same time, the naive `panic!(err)` attempt will lead to a compiler error that will spit out the correct solution:

```
error: format argument must be a string literal
 --> src/main.rs:3:12
  |
3 |     panic!(error);
  |            ^
  |
help: you might be missing a string literal to format with
  |
3 |     panic!("{}", error);
  |            +++++
```

Since we explicitly talk about interpolation two exercises down the line, I think it's a fine balance to strike.
