### ISSUE TITLE
`#[from]` macro used in `14_source` solution not explained

### ISSUE THREAD

**Issue by louwers** [mainmatter/100-exercises-to-learn-rust#183]
The solution to `14_source` uses `#[from]`:

https://github.com/mainmatter/100-exercises-to-learn-rust/blob/8fedc3ce13a0b90651508787ed47affac368c689/exercises/05_ticket_v2/14_source/src/lib.rs#L27

I don't think it is explained or introduced anywhere. I just used

```
    InvalidStatus { source: ParseStatusError },
```

for my solution.

**Comment by LukeMathWalker** [comment]
It is explained in https://rust-exercises.com/100-exercises/05_ticket_v2/14_source.html#implementing-source-using-thiserror!
