### ISSUE TITLE
Consider listing knowledge of recursion as a prerequisite of the course or linking to resources

### ISSUE THREAD

**Issue by illicitonion** [mainmatter/100-exercises-to-learn-rust#204]
I've run through this course with people who have learnt a programming language (JavaScript and/or Python) but who aren't familiar with recursion.

Knowledge of recursion is assumed in [one of the early exercises](https://github.com/mainmatter/100-exercises-to-learn-rust/blob/main/exercises/02_basic_calculator/05_factorial/src/lib.rs), and some familiarity with [factorials](https://github.com/mainmatter/100-exercises-to-learn-rust/blob/main/exercises/02_basic_calculator/05_factorial/src/lib.rs) and [Fibonacci numbers](https://github.com/mainmatter/100-exercises-to-learn-rust/blob/main/exercises/06_ticket_management/02_vec/src/lib.rs) is assumed.

While these are probably reasonable assumptions for programmers with professional experience, or computer science graduates, they may be new concepts for people learning programming through less traditional routes.

I think we should probably find a good introductory resource for recursion and link to it in the places it's assumed. Alternatively, I think it's reasonable to list it as a prerequisite (in the same way that we list "know a programming language" as a prerequisite), but I'd recommend if we do so we still link to a good introductory resource.

I'm happy to try to find such a resource to link to, if we agree this is worth solving.

**Comment by LukeMathWalker** [comment]
I appreciate the concern, but this would be overly zealous, in my opinion.
Learners can easily google what a factorial or a Fibonacci sequence is.
