### ISSUE TITLE
02_basic_calculator/08_overflow Ignores Dev Profile

### ISSUE THREAD

**Issue by JimLynchCodes** [mainmatter/100-exercises-to-learn-rust#206]
Hi, I'm on exercise 02_basic_calculator/08_overflow

I'm thinking the correct thing to do is add this to the bottom of Cargo.toml:
```
[profile.dev]
overflow-checks = false
```

But when I run the tests they still fail, with a warning saying this dev profile is being ignored...

> warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
> package:   /Users/jim/Git-Projects/100-exercises-to-learn-rust/exercises/02_basic_calculator/08_overflow/Cargo.toml

For some reason it thinks this directory is not the project root, but there are no Cargo.toml files in any parents directories...

What is the intended solution for this exercise?

Thanks

**Comment by c-git** [comment]
It's actually part of a workspace. If you go up to the root folder you'll see another `Cargo.toml` there. The solutions are on a branch here but I guess this one was a bit tricky to find if you hadn't found the other `Cargo.toml` https://github.com/mainmatter/100-exercises-to-learn-rust/blob/508224262e9ead0a622bc82c5486883812c85f55/Cargo.toml#L8

**Comment by LukeMathWalker** [comment]
Closing given @c-git's comment.
