### ISSUE TITLE
btree map into_iter

### ISSUE THREAD

**Issue by barkanido** [mainmatter/100-exercises-to-learn-rust#210]
Hey and thanks for this great repo!

I am looking for some directions on how to implement `IntoIterator` for `TicketStore`.

from the test it looks like the returned iterator is expected to yield on a `Ticket` but the 'natural' iterator supplied by `BTreeMap` yields both the key and the value as documented [here](https://doc.rust-lang.org/stable/alloc/collections/btree_map/struct.Iter.html).

This confuses me:
1. what would be the associated types of the returned iterator?
2. can this be done without collecting (memory allocation) into a Vec first, for example, using a `.map(|_, t| t)`. in that case, what should be the associated `IntoIter` type?

**Comment by LukeMathWalker** [comment]
It can—you have different methods on `BTreeMap` returning different kinds of iterators.
Look at the solution branch if you're still in doubt!
