### ISSUE TITLE
04_traits/05_trait_bounds: test fails due to missing Debug trait 

### ISSUE THREAD

**Issue by ghost** [mainmatter/100-exercises-to-learn-rust#218]
The exercise is to: 

`Add the necessary trait bounds to 'min' so that it compiles successfully.` 

I have added: 

```rust
pub fn min<T: PartialOrd + PartialEq + Eq + Ord>(left: T, right: T) -> T {
    if left <= right {
        left
    } else {
        right
    }
}
```

I get build errors for `Ticket cannot be formatted using '{:?}'`. I believe the test runner generates the `Ticket` struct but doesn't have the `#[derive(Debug)]` specified, so the build won't work.

**Comment by youssefhoumazen** [comment]
I believe adding PartialEq + Eq + Ord will require debug, just remove them because you will only need PartialOrd for comparison : ``` rust 
pub fn min<T: PartialOrd>(left: T, right: T) -> T {
    if left <= right {
        left
    } else {
        right
    }
} ```
