### ISSUE TITLE
Clarify sync trait explanation

### ISSUE THREAD

**Issue by iacri** [mainmatter/100-exercises-to-learn-rust#228]
I could not follow logically the explanation for the Sync trait:
>In order words: T: Sync means that &T is Send.
>[...]
>Sync doesn't imply Send
>[...]
>Send doesn't imply Sync

I think what has explained it better for me is [the rust book](https://doc.rust-lang.org/nomicon/send-and-sync.html):
>T is Sync if and only if &T is Send

At the same time, I think there is something that was being said in the Sync trait chapter of this course which has been lost on me. Is it about the fact that T being Sync doesn't give any kind of guarantee about T being Send (instead of &T)?

In any case, I think a rewording could help there, even if only to adjust the apparent logical discrepancy (first A => B, then A =/> B apparently)

**Comment by LukeMathWalker** [comment]
>  Is it about the fact that T being Sync doesn't give any kind of guarantee about T being Send (instead of &T)?

That's indeed the point being made here.
I'll adjust the wording to make things a bit clearer.
