### ISSUE TITLE
Question: practical reason for references to integral types?

### ISSUE THREAD

**Issue by HeavyMetalGeek** [mainmatter/100-exercises-to-learn-rust#24]
I just finished `03_ticket_v1` and was wondering why you would want to return a reference to an integral type?  Because a reference is `usize`, I can understand why you wouldn't want to copy types where `std::mem::size_of<T>() > std::mem::size_of<usize>`.  Is it just to reinforce the notion that we are returning a reference to a struct member?  Or are there other practical reasons?

Also, if there is a better venue for asking these sorts of questions, I'd be happy to utilize that in the future.

Thank you for putting this together!  I wish I would have had this when I started playing with Rust 3 or 4 years ago!

**Comment by LukeMathWalker** [comment]
> Is it just to reinforce the notion that we are returning a reference to a struct member? Or are there other practical reasons?

At that point in the course, we haven't yet talked about `Copy` or `Clone`, so we explicitly don't take advantage of the fact that integers are `Copy`. When that concept is introduced, then signatures of getters are changed to return the `Copy` type directly.
