### ISSUE TITLE
Questionable assignment in (06) ticket_management (11) mutable_slices

### ISSUE THREAD

**Issue by Burnus** [mainmatter/100-exercises-to-learn-rust#26]
Should the question on line 3 really be about `&mut [str]`, not `&mut str`? I mean, you can easily take an array here, but neither the tests nor the TODO indicate that you should.

**Comment by timmyjose** [comment]
In addition, `make_ascii_lowercase` is incorrect since it cannot handle Unicode, and it's not mentioned in the description that only ASCII characters are supported (granted the tests in the file only have ASCII).
