### ISSUE TITLE
Wrong requirements in chapter 3 task 2

### ISSUE THREAD

**Issue by Gaming4LifeDE** [mainmatter/100-exercises-to-learn-rust#29]
In chapter 3 (ticket v1) task 2 (validation) you say the following:

``` rust
    //   - the `title` should be at most 50 bytes long.
    //   - the `description` should be at most 500 bytes long.
```
The tests on the other hand state the following:

``` rust
    #[should_panic(expected = "Title cannot be longer than 50 characters")]
    fn title_cannot_be_longer_than_fifty_chars() {
        Ticket::new(overly_long_title(), valid_description(), "To-Do".into());
    }

    #[should_panic(expected = "Description cannot be longer than 500 characters")]
    fn description_cannot_be_longer_than_500_chars() {
        Ticket::new(valid_title(), overly_long_description(), "To-Do".into());
    }
```

This would be incorrect, as utf-8 characters can be more than one byte in size. (think ä,ß, etc.)

**Comment by LukeMathWalker** [comment]
We know use `bytes` consistently everywhere. Thanks!

**Comment by Gaming4LifeDE** [comment]
Might also be good to include an explanation for people, basically going like "Note this does not give you the length of a String in characters, since a lot of UTF-8 characters are longer than a single byte"

I think this would be a good thing to include since people will reference what they did in the exercises for later projects and might go something like "hey, I checked the length of a String before, let's see how I did it"

**Comment by c-git** [comment]
Yeah I thought about that as well but wasn't sure if it was covered later in the course. I did want to be cognizant of how many new concepts were introduced at the same time. But yeah it is worth mentioning somewhere.

**Comment by Gaming4LifeDE** [comment]
I think pointing it out would be enough in this case. I don't think it would be necessary to explain a way to get the character count in this chapter, that could be done elsewhere. You could even say "We are explaining this in more detail later" or something like that.
