### ISSUE TITLE
4.9: Flesh out the explanation of `Output`

### ISSUE THREAD

**Issue by thomasaarholt** [mainmatter/100-exercises-to-learn-rust#31]
I think 4.9 could benefit from an additional paragraph expanding on what `type Output;` does. 
In the solution for "[**4.13. Outro**](https://github.com/mainmatter/100-exercises-to-learn-rust/blob/907dbf957f7ded018bfddce9c30e08d730cbc110/exercises/04_traits/13_outro/src/lib.rs#L43-L50)", there is the line `type Output = SaturatingU16;`, which I _think_ could be `type Output = Self;`, since it is implemented _for_ `SaturatingU16`?

I guess my main point of confusion is, "Why do we need to create the Output type, when we can just specify the return type in the function signature below?" and "Why can't we just specify `-> Self` in the function signature, why do we need `-> Self::Output`?

**Comment by LukeMathWalker** [comment]
I've reworked 4.9 in eb0b4f7 to provide more details on what `Output` does, as well as remarks on the syntax. Thanks for pointing this out!
