### ISSUE TITLE
No "Further Reading" section in book 4.4 - Derive macros page

### ISSUE THREAD

**Issue by DrGFreeman** [mainmatter/100-exercises-to-learn-rust#34]
The [Macros](https://rust-exercises.com/04_traits/04_derive#macros) section of the book's **4.4 - Derive macros** page has a link to a [Further Reading](https://rust-exercises.com/04_traits/04_derive#further-reading) section but the subsection is missing from the page.

BTW, this an excellent learning resource, thank you for putting it together!

**Comment by LukeMathWalker** [comment]
Good catch, thank you!
