### ISSUE TITLE
Clarify *which* `Cargo` file should be modified in Basic Calculator/2.8 (Overflow)

### ISSUE THREAD

**Issue by Sensanaty** [mainmatter/100-exercises-to-learn-rust#5]
I'm loving this so far, but one issue I just ran into that made me look at the solutions was that modifying the `Cargo.toml` under `exercises/02_basic_calculator/08_overflow` wouldn't work when running `wr`, and you had to modify the *root level* `Cargo.toml` instead to get the expected overflow behavior.

As a beginner to Rust I was quite confused as to why this was failing/not working, so maybe specifying/clarifying how Cargo works exactly would be good before having people start modifying it? I had presumed that it would automatically pick up whatever is the closest `Cargo.toml` to the tests, but apparently that isn't the case.

For example, it would be nice to understand why it is that every single exercise has its own `Cargo.toml`, especially if it doesn't seem like these `Cargo` files are being respected? This might be covered in a latter exercise, in which case maybe introducing it earlier would be good?

This could also be a setup/local issue but I doubt it, as it's a fresh Rust install and I just opened the entire repo/folder in RustRover.

**Comment by LukeMathWalker** [comment]
We suggest in the [comment at the beginning of the exercise](https://github.com/mainmatter/100-exercises-to-learn-rust/blob/ee055245e525f97e1bb73ddb4cae372731a138dc/exercises/02_basic_calculator/08_overflow/src/lib.rs#L5) which manifest should be modified. Is that too easy to miss?

I'll evaluate the possibility of explaining earlier the package layout of a project.

**Comment by LukeMathWalker** [comment]
> For example, it would be nice to understand why it is that every single exercise has its own Cargo.toml, especially if it doesn't seem like these Cargo files are being respected? This might be covered in a latter exercise, in which case maybe introducing it earlier would be good?

The repository is organized as a Cargo _workspace_; therefore, the profile(s) must be configured at the workspace level.
It's more a matter of "who is in charge of what" than Cargo not respecting the (closest) project manifest.

**Comment by Sensanaty** [comment]
I think the wording there, `... the customization needs to be done in the `Cargo.toml`` makes it a big vague indeed. I had assumed it meant the closest one to the code you're touching, instead of the *root-level* one.

Imagine if someone were opening these exercises on a per-folder basis, without having the whole repo open. The one and only `Cargo.toml` they'd see would be the exercise one, and not the root one.

Just clarifying that you should edit the root `Cargo.toml` would help here I think!

**Comment by LukeMathWalker** [comment]
No worries at all!
