### ISSUE TITLE
Question: how do I reset wr database?

### ISSUE THREAD

**Issue by chiroptical** [mainmatter/100-exercises-to-learn-rust#54]
I have this issue after upgrading my fork.

```
error: manifest path `exercises/04_traits/05_str_slice/Cargo.toml` does not exist
	❌ (04) traits - (05) str_slice
```

I only noticed this because of https://rust-exercises.com/04_traits/05_trait_bounds.

Might be nice to have `wr reset --chapter 4 --exercise 5` when the order of exercises changes?

**Comment by chiroptical** [comment]
If anyone else comes across this you can just remove the non-existent exercise.

```
➤ litecli exercises/progress.db
LiteCli: 1.11.0 (SQLite: 3.45.3)
GitHub: https://github.com/dbcli/litecli
exercises/progress.db> delete from open_exercises where chapter = '04_traits' and exercise = '05_str_slice';
```

**Comment by LukeMathWalker** [comment]
The general recommendation is to avoid pulling after you start, but @chiroptical's solution is a solid workaround. I don't expect the schema to change there!
