### ISSUE TITLE
How to run the gitbook locally like the rust book?

### ISSUE THREAD

**Issue by keshav-c** [mainmatter/100-exercises-to-learn-rust#61]
Hi, First off thank you so much for this book. I was thinking, now that I have cloned this repository, is there any way to serve this git book locally? Like for example how you can open the rust book using `rustup doc --book`.

**Comment by c-git** [comment]
I don't know if there is an easy way to build a local version but you can print it to PDF using the button in the top right 
![image](https://github.com/mainmatter/100-exercises-to-learn-rust/assets/43485962/a95821c9-4eb3-4767-a3f0-3f366f39fc8a)

**Comment by gumikola** [comment]
Are you probably looking for mdbook?

Ex. `$mdbook serve book/`

**Comment by keshav-c** [comment]
@gumikola That is exactly what I was looking for. Thank you.

**Comment by keshav-c** [comment]
@gumikola That is exactly what I was looking for. Thank you.
