### ISSUE TITLE
04_traits/12_copy passes even without implementing wrapping add

### ISSUE THREAD

**Issue by vitalie-cracan** [mainmatter/100-exercises-to-learn-rust#64]
04_traits/12_copy passes even without implementing wrapping, because 02_basic_calculator/08_overflow added it to dev profile in Cargo.toml.

**Comment by c-git** [comment]
Interestingly until you mentioned it I never even thought that wasn't intentional. I "relied" on that for the test to pass and never looked at the official solutions to see they intended for use to use `wrapping_add`. I thought it was jut to give us practice implementing the Add trait.

**Comment by LukeMathWalker** [comment]
Good catch—I fixed this with a package-specific override.
