### ISSUE TITLE
Question about book 3.7 setter

### ISSUE THREAD

**Issue by wintermorn1ng** [mainmatter/100-exercises-to-learn-rust#73]
As a Rust beginner it's nice to come across such great tutorials, thanks to the contributors.

I had an issue while reading section 3.7: [link](https://rust-exercises.com/03_ticket_v1/07_setters#taking-mut-self-as-input)

> &mut-setters have a downside: you can't chain multiple calls together. Since they don't return the modified Ticket instance, you can't call another setter on the result of the first one. You have to call each setter separately:

I was curious if it was possible to chain calls by returning `&mut Self`, and after trying it seems to work.
[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=11e950e2e528112d0ac57fbdbd7d062b)
[gist link](https://gist.github.com/rust-play/37075e88e2270adc623fbf0aa81a93a0)

So I'm not sure if there are downsides to this implementation that lead to this description in the book?

**Comment by c-git** [comment]
I thought the same thing actually, but then thought more about it and realized that in practice when someone uses the `&mut` approach they tend not to return anything. And since you may not be the one who writes the API and only consumes it, then the downside kinda stays.

**Comment by wintermorn1ng** [comment]
> I thought the same thing actually, but then thought more about it and realized that in practice when someone uses the `&mut` approach they tend not to return anything. And since you may not be the one who writes the API and only consumes it, then the downside kinda stays.

Thanks for the reply, maybe I haven't felt this drawback yet because I have so little experience with Rust development, but I think I understand what you mean, thanks again.
