### ISSUE TITLE
updated my local clone from main, now I'm stuck in an non-existent exercise

### ISSUE THREAD

**Issue by jstitch** [mainmatter/100-exercises-to-learn-rust#74]
I had unlocked an old exercice, chapter 4, ex 5 about string slices.

But by following the online book I noted that ex 5 is now about trait bounds. So I decided  to update from origin and rebase my way back to where I was.

Now wr is stuck on a chapter 5 about string slices which doesn't exists, it's now chapter 6. How can I solve this?

```
	❌ (04) traits - (05) str_slice
error: manifest path `exercises/04_traits/05_str_slice/Cargo.toml` does not exist
```

**Comment by jstitch** [comment]
wow, hacked my way around it... found a progress.db file in the exercises subdir. Guessed it could be a sqlite3 file, opened it and found a single table for the open exercises. Found the faulty register:

```
sqlite> .schema
CREATE TABLE open_exercises (
                chapter TEXT NOT NULL,
                exercise TEXT NOT NULL,
                solved INTEGER NOT NULL,
                PRIMARY KEY (chapter, exercise)
            );
sqlite> SELECT * FROM open_exercises;
... lots of registers...
04_traits|05_str_slice|0
```

and just deleted with plain SQL: ` DELETE FROM open_exercises WHERE chapter='04_traits' AND exercise='05_str_slice'; `

Guess this could be a request for adding features to wr to manage this kind of things...

**Comment by HlgdB** [comment]
Also encountered the same problem😢

**Comment by c-git** [comment]
Were you able to follow the workaround to get past it?

**Comment by LukeMathWalker** [comment]
Fixed as part of https://github.com/mainmatter/rust-workshop-runner/issues/12. Re-install `wr` to get the fix!
