### ISSUE TITLE
Possible solution optimization in 02_basic_calculator/07_for

### ISSUE THREAD

**Issue by jakeheke75** [mainmatter/100-exercises-to-learn-rust#76]
Hello @LukeMathWalker,

In this solution can't we maybe start the `for` loop from number 2? In this way we can optimize, skip 1 loop and avoid multiplying the `result` by 1:
https://github.com/mainmatter/100-exercises-to-learn-rust/blob/1ead9e42e60eca8b41f2a1abf6adcca2552c9b89/exercises/02_basic_calculator/07_for/src/lib.rs#L4
Thanks for your fantastic course and to make it free for all.
Ciao

**Comment by LukeMathWalker** [comment]
You can, but I opted for the "obvious" solution—performance is not the point of the exercise.
