### ISSUE TITLE
04_traits/09_from Into<&str> for String

### ISSUE THREAD

**Issue by eugenefil** [mainmatter/100-exercises-to-learn-rust#81]
In the section "&str to String" there is a paragraph:

> We've been primarily using .into(), though.
> If you check out the [implementors of Into](https://doc.rust-lang.org/std/convert/trait.Into.html#implementors) you won't find Into<&str> for String. What's going on?

Is `Into<&str> for String` really what we're looking for? That converts String into &str. But, according to the section header, we want the opposite - hypothetical `Into<String> for &str`. No?

**Comment by LukeMathWalker** [comment]
You're right. This has been fixed now.
