### ISSUE TITLE
How to run the Web Version on my Localhost

### ISSUE THREAD

**Issue by shoutmarble** [mainmatter/100-exercises-to-learn-rust#83]
How can I run [100-exercises-to-learn-rust](https://github.com/mainmatter/100-exercises-to-learn-rust) hosted on my localhost via the Web.

I prefer the Web format version but I get
```
Playground Communication: timeout
```

**Comment by LukeMathWalker** [comment]
Links and buttons for the Rust playground will always try to communicate with https://play.rust-lang.org/
