### ISSUE TITLE
Interior mutability exercice question 

### ISSUE THREAD

**Issue by EmmaLa** [mainmatter/100-exercises-to-learn-rust#88]
So basically on the drop method i had to put this code : 

```
fn drop(&mut self) {
    *(*self.counter).borrow_mut() += 1;                                       
} 
```

Instead of this : 

```
fn drop(&mut self) {
    *self.counter.borrow_mut() += 1;                                   
} 
```

When trying the latter i was getting this error : 

cannot use `+=` on type `Rc<RefCell<usize>>`

Which make sense because Rc implements BorrowMut that return a mut reference to itself.
So when we call self.counter.borrow_mut() it returns a &mut Rc and then when we dereference we just get Rc so "+=" don't work.

You can tell me if i'm the only one that had issues using the solution on the Interior Mutability exercice.

**Comment by c-git** [comment]
Was going to compare my answer but I'm not sure which exercise. Can you give the chapter and exercise number?

**Comment by EmmaLa** [comment]
> Was going to compare my answer but I'm not sure which exercise. Can you give the chapter and exercise number?

Oups i should have put the link, this is for this one [07_threads/06_interior_mutability](https://github.com/mainmatter/100-exercises-to-learn-rust/blob/solutions/exercises/07_threads/06_interior_mutability/src/lib.rs#L20) i put the link to the line directly.

**Comment by c-git** [comment]
Based on the information available I'd say check your imports. I don't think `BorrowMut` for `Rc` is in the prelude so you probably brought it into scope and that's why you need to do the extra stuff. If you remove it then you should get the one from `RefCell`. I have the same thing in my code as what you shared and it works for me.

**Comment by EmmaLa** [comment]
> Based on the information available I'd say check your imports. I don't think `BorrowMut` for `Rc` is in the prelude so you probably brought it into scope and that's why you need to do the extra stuff. If you remove it then you should get the one from `RefCell`. I have the same thing in my code as what you shared and it works for me.

Indeed this was because of an import, arg LSP... I got a : use std::borrow::BorrowMut; that has been added and is was not compiling because of that.
So i learned a new thing today thanks for your help!

I'll close my issue thanks!

**Comment by c-git** [comment]
No worries happy to help, bumped my toe on that stone before (same way to, RA was "helping"...).
