### ISSUE TITLE
Suggestion for 03 Ticket - 02 Validation

### ISSUE THREAD

**Issue by chiroptical** [mainmatter/100-exercises-to-learn-rust#9]
Two notes

- Requiring specific `panic` messages for the errors is a little annoying
- Technically this is wrong `Title cannot be longer than 50 characters` , from https://doc.rust-lang.org/std/string/struct.String.html#method.len
```
Returns the length of this String, in bytes, not chars or graphemes. In other words, it might not be what a human considers the length of the string.
```
In the exercise it asks `the 'title' should be at most 50 bytes long`

**Comment by LukeMathWalker** [comment]
We know use `bytes` consistently everywhere. Thanks!
